-- Criação da tabela de Formas de Pagamento
create table formas_pagamento (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  nome text not null,
  valor_ref text, -- identificador unico opcional (ex: pix, boleto)
  config_json jsonb -- para configs futuras
);

-- Habilita RLS (Segurança)
alter table formas_pagamento enable row level security;

-- Políticas de Acesso
create policy "Usuários podem ver suas proprias formas de pagamento"
  on formas_pagamento for select
  using ( auth.uid() = user_id );

create policy "Usuários podem inserir suas proprias formas de pagamento"
  on formas_pagamento for insert
  with check ( auth.uid() = user_id );

create policy "Usuários podem atualizar suas proprias formas de pagamento"
  on formas_pagamento for update
  using ( auth.uid() = user_id );

create policy "Usuários podem deletar suas proprias formas de pagamento"
  on formas_pagamento for delete
  using ( auth.uid() = user_id );
